(()=>{
'use strict';
const VERSION='5.0.0', STORE='eurolab.v5', OLD='eurolab.v4';
const EM_FREQ={1:186,2:185,3:192,4:200,5:202,6:193,7:201,8:190,9:185,10:215,11:191,12:197,13:202,14:203,15:199,16:193,17:215,18:176,19:218,20:203,21:213,22:154,23:222,24:201,25:208,26:205,27:205,28:190,29:217,30:197,31:187,32:179,33:173,34:199,35:206,36:185,37:211,38:199,39:194,40:179,41:181,42:223,43:180,44:224,45:207,46:175,47:185,48:193,49:197,50:210};
const ED_FREQ={1:40,2:40,3:51,4:51,5:38,6:35,7:42,8:51,9:42,10:39,11:40,12:38,13:39,14:42,15:50,16:40,17:41,18:43,19:52,20:38,21:56,22:55,23:56,24:53,25:39,26:39,27:42,28:44,29:35,30:48,31:39,32:43,33:46,34:41,35:38,36:29,37:52,38:45,39:37,40:39};
const ED_DREAM={1:65,2:51,3:64,4:53,5:55};
const money=n=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const dpt=s=>s?new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(s+'T12:00:00')):'—';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();
const sort=a=>[...new Set((a||[]).map(Number))].sort((x,y)=>x-y);
const lineKey=x=>`${x.game}|${x.drawDate}|${sort(x.numbers).join('-')}|${sort(x.extras).join('-')}`;
const baseState=()=>({version:VERSION,tickets:[],results:{em:[],ed:[],m1:[]},m1Codes:[],budget:20,filter:'all',pendingCaptures:[]});
function seed(s){
 const tickets=[
  {id:'em-20260731',game:'em',drawDate:'2026-07-31',numbers:[18,20,23,44,47],extras:[1,2],cost:2.5,prize:0,m1Code:'NDL16327',m1DrawDate:'2026-07-31'},
  {id:'em-20260804',game:'em',drawDate:'2026-08-04',numbers:[7,19,32,42,46],extras:[3,11],cost:2.5,prize:0,m1Code:'NGZ37292',m1DrawDate:'2026-08-28'},
  {id:'ed-20260810',game:'ed',drawDate:'2026-08-10',numbers:[6,15,22,29,32,37],extras:[3],cost:2.5,prize:0}
 ];
 const results={
  em:[
   {date:'2026-07-31',numbers:[10,24,25,31,45],extras:[4,5],official:true,source:'Jogos Santa Casa'},
   {date:'2026-08-04',numbers:[25,30,34,46,50],extras:[1,12],official:true,source:'Jogos Santa Casa'},
   {date:'2026-08-07',numbers:[26,29,35,38,47],extras:[1,2],official:true,source:'Jogos Santa Casa'}
  ],
  ed:[
   {date:'2026-08-10',numbers:[7,9,10,26,33,40],extras:[1],official:true,source:'Resultado europeu oficial'}
  ],
  m1:[{date:'2026-07-31',code:'NFN37781',official:true,source:'Jogos Santa Casa'}]
 };
 const codes=[
  {id:'m1-ngz',code:'NGZ37292',drawDate:'2026-08-28',registered:'2026-08-03',status:'pending',prize:0},
  {id:'m1-nlb',code:'NLB00955',drawDate:'2026-08-28',registered:'2026-08-07',status:'pending',prize:0}
 ];
 tickets.forEach(t=>{if(!s.tickets.some(x=>lineKey(x)===lineKey(t)))s.tickets.push(t)});
 Object.keys(results).forEach(g=>results[g].forEach(r=>{if(!s.results[g].some(x=>x.date===r.date))s.results[g].push(r)}));
 codes.forEach(c=>{if(!s.m1Codes.some(x=>x.code===c.code))s.m1Codes.push(c)});
 if(!s.pendingCaptures?.length)s.pendingCaptures=[{game:'ed',registered:'2026-08-14',label:'EuroDreams registado a 14/08 — chave ainda não capturada'},{game:'em',registered:'2026-08-07',label:'Euromilhões de 07/08 — chave não visível no screenshot'}];
 return s;
}
function migrate(){
 let s;try{s=JSON.parse(localStorage.getItem(STORE)||'null')}catch{}
 if(!s){s=baseState();try{const o=JSON.parse(localStorage.getItem(OLD)||'null');if(o?.tickets)s.tickets=o.tickets.map(t=>({id:t.id||uid(),game:'em',drawDate:t.drawDate,numbers:t.numbers||[],extras:t.stars||[],cost:Number(t.cost||2.5),prize:Number(t.prize||0),m1Code:t.mCode||'',m1DrawDate:''}));if(o?.results)s.results.em=o.results.map(r=>({date:r.date,numbers:r.numbers||[],extras:r.stars||[],official:r.official!==false,source:r.source||'Importado'}));if(Number.isFinite(o?.budget))s.budget=o.budget}catch{}}
 s.results=s.results||{em:[],ed:[],m1:[]};s.results.em=s.results.em||[];s.results.ed=s.results.ed||[];s.results.m1=s.results.m1||[];s.m1Codes=s.m1Codes||[];s.pendingCaptures=s.pendingCaptures||[];return seed(s);
}
const state=migrate();
function save(){state.version=VERSION;localStorage.setItem(STORE,JSON.stringify(state))}
function resultFor(t){return (state.results[t.game]||[]).find(r=>r.date===t.drawDate)||null}
function hits(t){const r=resultFor(t);if(!r)return null;return {n:t.numbers.filter(n=>r.numbers.includes(n)).length,e:t.extras.filter(n=>r.extras.includes(n)).length}}
function category(t){const h=hits(t);if(!h)return 'Por verificar';if(t.game==='ed'){if(h.n===6&&h.e===1)return '1.º prémio';if(h.n===6)return '2.º prémio';if(h.n===5)return '3.º prémio';if(h.n===4)return '4.º prémio';if(h.n===3)return '5.º prémio';if(h.n===2)return '6.º prémio';return 'Sem prémio'}const map={'5-2':'1.º prémio','5-1':'2.º prémio','5-0':'3.º prémio','4-2':'4.º prémio','4-1':'5.º prémio','3-2':'6.º prémio','4-0':'7.º prémio','2-2':'8.º prémio','3-1':'9.º prémio','3-0':'10.º prémio','1-2':'11.º prémio','2-1':'12.º prémio','2-0':'13.º prémio'};return map[`${h.n}-${h.e}`]||'Sem prémio'}
function gameName(g){return g==='em'?'Euromilhões':g==='ed'?'EuroDreams':'M1lhão'}
function balls(x){if(!x)return '<span class="muted">Sem resultado</span>';const excls=x.game==='ed'?'dream':'extra';return `<div class="balls">${x.numbers.map(n=>`<span class="ball">${n}</span>`).join('')}<span class="plus">+</span>${x.extras.map(n=>`<span class="ball ${excls}">${n}</span>`).join('')}</div>`}
function latest(g){return [...(state.results[g]||[])].sort((a,b)=>b.date.localeCompare(a.date))[0]||null}
function spentAllocation(){let em=0,ed=0,m1=0;state.tickets.forEach(t=>{if(t.game==='ed')ed+=t.cost;else{const mc=t.m1Code?Math.min(.3,t.cost):0;m1+=mc;em+=Math.max(0,t.cost-mc)}});state.m1Codes.forEach(c=>{if(!state.tickets.some(t=>t.m1Code===c.code))m1+=.3});return {em,ed,m1}}
function totals(){const spent=state.tickets.reduce((a,t)=>a+Number(t.cost||0),0)+state.m1Codes.filter(c=>!state.tickets.some(t=>t.m1Code===c.code)).reduce(a=>a+.3,0);const won=state.tickets.reduce((a,t)=>a+Number(t.prize||0),0)+state.m1Codes.reduce((a,c)=>a+Number(c.prize||0),0);return {spent,won,balance:won-spent,roi:spent?((won-spent)/spent*100):0}}
function renderKPIs(){const t=totals();$('#kSpent').textContent=money(t.spent);$('#kWon').textContent=money(t.won);$('#kBalance').textContent=money(t.balance);$('#kROI').textContent=`${t.roi.toFixed(1)}%`;$('#kBalance').className=t.balance>=0?'good':'bad';$('#kROI').className=t.roi>=0?'good':'bad'}
function renderGameCards(){['em','ed'].forEach(g=>{const r=latest(g),box=$(`#latest-${g}`);box.innerHTML=`<div class="gamehead"><div><span class="tag ${g}">${gameName(g)}</span><h3>${r?dpt(r.date):'Sem resultado'}</h3></div><span class="status">${r?.official?'Oficial':'Manual'}</span></div>${balls(r?{...r,game:g}:null)}<div class="mini muted">${r?.source||''}</div>`});const pending=state.m1Codes.filter(c=>c.status==='pending');$('#latest-m1').innerHTML=`<div class="gamehead"><div><span class="tag m1">M1lhão</span><h3>Próximo sorteio: 28/08/2026</h3></div><span class="status pending">${pending.length} códigos ativos</span></div><div class="rows">${pending.map(c=>`<div class="rowitem"><div><span class="m1code">${c.code.slice(0,3)} ${c.code.slice(3)}</span><div class="mini muted">Registado ${dpt(c.registered)}</div></div><b>28/08</b></div>`).join('')}</div>`}
function barChart(){const a=spentAllocation(),wins={em:state.tickets.filter(t=>t.game==='em').reduce((x,t)=>x+Number(t.prize||0),0),ed:state.tickets.filter(t=>t.game==='ed').reduce((x,t)=>x+Number(t.prize||0),0),m1:state.m1Codes.reduce((x,t)=>x+Number(t.prize||0),0)};const vals=['em','ed','m1'].flatMap(g=>[a[g],wins[g]]),max=Math.max(1,...vals);let svg='<svg class="svgchart" viewBox="0 0 600 220"><line class="axis" x1="45" y1="190" x2="575" y2="190"/>';['em','ed','m1'].forEach((g,i)=>{const x=90+i*170,h1=a[g]/max*145,h2=wins[g]/max*145;svg+=`<rect class="bar1" x="${x}" y="${190-h1}" width="42" height="${h1}" rx="7"/><rect class="bar2" x="${x+50}" y="${190-h2}" width="42" height="${h2}" rx="7"/><text class="chartlabel" x="${x+45}" y="210" text-anchor="middle">${gameName(g)}</text>`});$('#barChart').innerHTML=svg+'</svg>'}
function donut(){const a=spentAllocation(),total=a.em+a.ed+a.m1||1,p1=a.em/total*100,p2=a.ed/total*100;$('#donut').style.background=`conic-gradient(#42b8ff 0 ${p1}%,#a36cff ${p1}% ${p1+p2}%,#f0c34a ${p1+p2}% 100%)`;$('#donutTotal').textContent=money(total);$('#donutLegend').innerHTML=`<div><span class="dot" style="background:#42b8ff"></span>Euromilhões ${money(a.em)}</div><div><span class="dot" style="background:#a36cff"></span>EuroDreams ${money(a.ed)}</div><div><span class="dot" style="background:#f0c34a"></span>M1lhão ${money(a.m1)}</div>`}
function lineChart(){const events=[];state.tickets.forEach(t=>events.push({date:t.drawDate,v:-Number(t.cost||0)}));state.m1Codes.filter(c=>!state.tickets.some(t=>t.m1Code===c.code)).forEach(c=>events.push({date:c.registered,v:-.3}));state.tickets.forEach(t=>{if(t.prize)events.push({date:t.drawDate,v:Number(t.prize)})});state.m1Codes.forEach(c=>{if(c.prize)events.push({date:c.drawDate,v:Number(c.prize)})});events.sort((a,b)=>a.date.localeCompare(b.date));let cum=0,pts=events.map(e=>({date:e.date,v:(cum+=e.v)}));if(!pts.length){$('#lineChart').innerHTML='<div class="empty">Sem dados</div>';return}const min=Math.min(...pts.map(p=>p.v),0),max=Math.max(...pts.map(p=>p.v),0),range=max-min||1;const coords=pts.map((p,i)=>({x:45+(i/(Math.max(1,pts.length-1)))*520,y:175-((p.v-min)/range)*135,...p}));$('#lineChart').innerHTML=`<svg class="svgchart" viewBox="0 0 600 220"><line class="axis" x1="45" y1="190" x2="575" y2="190"/><path class="linepath" d="${coords.map((p,i)=>(i?'L':'M')+p.x+' '+p.y).join(' ')}"/>${coords.map(p=>`<circle class="linepoint" cx="${p.x}" cy="${p.y}" r="4"><title>${dpt(p.date)} · ${money(p.v)}</title></circle>`).join('')}</svg>`}
function ticketRow(t){const h=hits(t),cat=category(t),cls=cat==='Por verificar'?'pending':cat==='Sem prémio'?'lose':'win';return `<tr><td><span class="tag ${t.game}">${gameName(t.game)}</span></td><td>${dpt(t.drawDate)}</td><td>${t.numbers.join(' · ')} + ${t.extras.join(' · ')}</td><td>${h?`${h.n}+${h.e}`:'—'}</td><td><span class="status ${cls}">${cat}</span></td><td>${money(t.cost)}</td><td>${money(t.prize||0)}</td><td><button class="btn ghost mini" data-edit="${t.id}">Editar</button></td></tr>`}
function renderTickets(){const f=$('#ticketFilter').value||'all',list=state.tickets.filter(t=>f==='all'||t.game===f).sort((a,b)=>b.drawDate.localeCompare(a.drawDate));$('#ticketRows').innerHTML=list.map(ticketRow).join('')||'<tr><td colspan="8" class="empty">Sem apostas.</td></tr>'}
function renderM1(){const win=latest('m1');state.m1Codes.forEach(c=>{if(win&&c.drawDate===win.date){c.status=c.code===win.code?'win':'lose';if(c.status==='win'&&!c.prize)c.prize=1000000}});save();$('#m1List').innerHTML=state.m1Codes.sort((a,b)=>b.drawDate.localeCompare(a.drawDate)).map(c=>`<div class="card"><div class="gamehead"><div><span class="m1code">${c.code.slice(0,3)} ${c.code.slice(3)}</span><div class="muted">Sorteio ${dpt(c.drawDate)}</div></div><span class="status ${c.status==='pending'?'pending':c.status==='win'?'win':'lose'}">${c.status==='pending'?'Em jogo':c.status==='win'?'Premiado':'Sem prémio'}</span></div>${c.status==='pending'?'<div class="notice">Este código mantém-se ativo até ao sorteio de 28/08. Não é eliminado pelos sorteios semanais do Euromilhões.</div>':''}</div>`).join('')}
function freqGrid(){const mode=$('#analysisGame').value,source=mode==='ed'?ED_FREQ:EM_FREQ,max=Math.max(...Object.values(source));$('#freqGrid').innerHTML=Object.entries(source).map(([n,v])=>`<div class="freqcell"><i style="height:${v/max*100}%"></i><span>${n}</span><small>${v}x</small></div>`).join('');$('#analysisNote').textContent=mode==='ed'?'Frequências históricas oficiais do EuroDreams, usadas apenas como contexto. Não aumentam a probabilidade do próximo sorteio.':'Frequências históricas do Euromilhões, usadas apenas como contexto. Não tornam números “quentes” mais prováveis.';$('#oddsText').innerHTML=mode==='ed'?'<b>EuroDreams:</b> 6 de 40 + 1 Sonho de 5. 1.º prémio: 1 em 19.191.900 por aposta simples.':'<b>Euromilhões:</b> 5 de 50 + 2 estrelas de 12. Jackpot: 1 em 139.838.160 por aposta simples.'}
function rnd(max){if(crypto?.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return 1+(a[0]%max)}return 1+Math.floor(Math.random()*max)}
function candidate(game){const n=[],e=[];const nc=game==='ed'?6:5,nmax=game==='ed'?40:50,ec=game==='ed'?1:2,emax=game==='ed'?5:12;while(n.length<nc){const x=rnd(nmax);if(!n.includes(x))n.push(x)}while(e.length<ec){const x=rnd(emax);if(!e.includes(x))e.push(x)}return {game,numbers:sort(n),extras:sort(e)}}
function score(l,mode){const n=l.numbers,odd=n.filter(x=>x%2).length,cut=l.game==='ed'?20:25,low=n.filter(x=>x<=cut).length,span=n[n.length-1]-n[0],mean=n.reduce((a,b)=>a+b,0)/n.length;let s=0;if(Math.abs(odd-n.length/2)<=1)s+=25;if(Math.abs(low-n.length/2)<=1)s+=22;if(span>=(l.game==='ed'?24:30))s+=18;if(mean>=(l.game==='ed'?16:20)&&mean<=(l.game==='ed'?25:35))s+=10;const endings=new Set(n.map(x=>x%10)).size;s+=endings*3;if(mode==='share')s+=n.filter(x=>x>31).length*9;if(mode==='history'){const f=l.game==='ed'?ED_FREQ:EM_FREQ,sf=l.game==='ed'?ED_DREAM:null;s+=n.reduce((a,x)=>a+(f[x]||0),0)/n.length*.12;if(sf)s+=(sf[l.extras[0]]||0)*.12}return s+Math.random()*8}
function generate(game,mode='balanced'){let best=null,bs=-1e9;for(let i=0;i<1200;i++){const c=candidate(game),sc=score(c,mode);if(sc>bs){best=c;bs=sc}}return best}
function renderGenerated(){const game=$('#genGame').value,mode=$('#genMode').value,count=Math.max(1,Math.min(10,Number($('#genCount').value)||1)),lines=[];for(let i=0;i<count;i++){let l;do{l=generate(game,mode)}while(lines.some(x=>x.numbers.join()==l.numbers.join()&&x.extras.join()==l.extras.join()));lines.push(l)}$('#generated').innerHTML=lines.map((l,i)=>`<div class="card"><b>Linha ${i+1}</b>${balls(l)}<button class="btn ghost mini" data-copyline="${i}">Copiar</button></div>`).join('');window.__generated=lines;$('#genCost').textContent=money(count*2.5);$('#genOdds').textContent=game==='ed'?`1 em ${Math.round(19191900/count).toLocaleString('pt-PT')}`:`1 em ${Math.round(139838160/count).toLocaleString('pt-PT')}`}
function buildPicker(){const game=$('#betGame').value,max=game==='ed'?40:50,ec=game==='ed'?1:2,emax=game==='ed'?5:12;$('#numPicker').innerHTML=Array.from({length:max},(_,i)=>`<button type="button" class="pick" data-num="${i+1}">${i+1}</button>`).join('');$('#extraPicker').innerHTML=Array.from({length:emax},(_,i)=>`<button type="button" class="pick ${game==='ed'?'dream':'extra'}" data-extra="${i+1}">${i+1}</button>`).join('');$('#pickLabel').textContent=game==='ed'?'Escolhe 6 números e 1 Nº de Sonho':'Escolhe 5 números e 2 estrelas';$('#betCost').value='2.50';$('#m1Fields').classList.toggle('hide',game==='ed');$('#betDate').value=nextDraw(game);$('#extraPicker').dataset.max=ec;$('#numPicker').dataset.max=game==='ed'?6:5}
function nextDraw(game){const now=new Date(),days=game==='ed'?[1,4]:[2,5];for(let a=0;a<8;a++){const d=new Date(now);d.setDate(now.getDate()+a);if(days.includes(d.getDay()))return d.toISOString().slice(0,10)}return now.toISOString().slice(0,10)}
function selected(box){return $$(`${box} .pick.on`).map(b=>Number(b.dataset.num||b.dataset.extra))}
function togglePick(e){const b=e.target.closest('.pick');if(!b)return;const box=b.parentElement,max=Number(box.dataset.max);if(!b.classList.contains('on')&&box.querySelectorAll('.on').length>=max)return;b.classList.toggle('on')}
function clearBet(){ $('#betId').value='';$('#betForm').reset();$('#betGame').value='em';buildPicker() }
function saveBet(e){e.preventDefault();const game=$('#betGame').value,numbers=sort(selected('#numPicker')),extras=sort(selected('#extraPicker')),needN=game==='ed'?6:5,needE=game==='ed'?1:2;if(numbers.length!==needN||extras.length!==needE){alert(`Seleciona ${needN} números e ${needE} ${game==='ed'?'Nº de Sonho':'estrelas'}.`);return}const id=$('#betId').value||uid(),t={id,game,drawDate:$('#betDate').value,numbers,extras,cost:Number($('#betCost').value||2.5),prize:Number($('#betPrize').value||0)};if(game==='em'){t.m1Code=$('#betM1').value.trim().replace(/\s+/g,'').toUpperCase();t.m1DrawDate=$('#betM1Date').value;if(t.m1Code&&!state.m1Codes.some(c=>c.code===t.m1Code))state.m1Codes.push({id:'m1-'+uid(),code:t.m1Code,drawDate:t.m1DrawDate||'2026-08-28',registered:t.drawDate,status:'pending',prize:0})}const i=state.tickets.findIndex(x=>x.id===id);i>=0?state.tickets[i]=t:state.tickets.push(t);save();clearBet();renderAll();go('bets')}
function editBet(id){const t=state.tickets.find(x=>x.id===id);if(!t)return;go('bets');$('#betId').value=t.id;$('#betGame').value=t.game;buildPicker();$('#betDate').value=t.drawDate;$('#betCost').value=t.cost;$('#betPrize').value=t.prize||0;$('#betM1').value=t.m1Code||'';$('#betM1Date').value=t.m1DrawDate||'';t.numbers.forEach(n=>$(`#numPicker [data-num="${n}"]`)?.classList.add('on'));t.extras.forEach(n=>$(`#extraPicker [data-extra="${n}"]`)?.classList.add('on'))}
function resultCards(){['em','ed'].forEach(g=>{const list=[...(state.results[g]||[])].sort((a,b)=>b.date.localeCompare(a.date));$(`#result-${g}`).innerHTML=list.slice(0,8).map(r=>`<div class="rowitem"><div><b>${dpt(r.date)}</b>${balls({...r,game:g})}</div><span class="status">${r.official?'Oficial':'Manual'}</span></div>`).join('')||'<div class="empty">Sem resultados.</div>'})}
function pending(){ $('#pendingList').innerHTML=(state.pendingCaptures||[]).map(x=>`<div class="rowitem"><div><span class="tag ${x.game}">${gameName(x.game)}</span><strong>${x.label}</strong></div><span class="status pending">A completar</span></div>`).join('')||'<div class="empty">Tudo completo.</div>' }
async function sync(){const el=$('#syncState');el.textContent='A atualizar resultados…';try{const r=await fetch('latest-results.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();['em','ed','m1'].forEach(g=>{const x=d[g];if(!x)return;if(g==='m1'){if(x.code&&!state.results.m1.some(y=>y.date===x.date))state.results.m1.push(x)}else if(x.numbers?.length&&!state.results[g].some(y=>y.date===x.date))state.results[g].push({...x,extras:x.extras||x.stars||x.dream||[]})});save();renderAll();el.textContent='Resultados sincronizados';}catch{el.textContent='Sem ligação à fonte automática · dados locais mantidos'}}
function go(id){$$('.page').forEach(p=>p.classList.toggle('on',p.id===id));$$('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.page===id));scrollTo(0,0)}
function renderAll(){renderKPIs();renderGameCards();barChart();donut();lineChart();renderTickets();renderM1();freqGrid();resultCards();pending();$('#version').textContent=VERSION;$('#budget').value=state.budget}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)go(b.dataset.page)});$('#ticketFilter').addEventListener('change',renderTickets);$('#analysisGame').addEventListener('change',freqGrid);$('#genGame').addEventListener('change',renderGenerated);$('#genMode').addEventListener('change',renderGenerated);$('#genCount').addEventListener('input',renderGenerated);$('#generate').addEventListener('click',renderGenerated);$('#betGame').addEventListener('change',buildPicker);$('#numPicker').addEventListener('click',togglePick);$('#extraPicker').addEventListener('click',togglePick);$('#betForm').addEventListener('submit',saveBet);$('#clearBet').addEventListener('click',clearBet);$('#syncBtn').addEventListener('click',sync);$('#budget').addEventListener('change',()=>{state.budget=Math.max(0,Number($('#budget').value)||0);save()});document.body.addEventListener('click',e=>{const ed=e.target.closest('[data-edit]');if(ed)editBet(ed.dataset.edit);const cp=e.target.closest('[data-copyline]');if(cp){const l=window.__generated?.[Number(cp.dataset.copyline)];if(l)navigator.clipboard?.writeText(`${l.numbers.join(' ')} + ${l.extras.join(' ')}`)}});
$('#exportBtn').addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='euro-lab-backup.json';a.click()});
$('#importFile').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const d=JSON.parse(rd.result);Object.assign(state,d);save();renderAll();alert('Dados importados.')}catch{alert('Ficheiro inválido.')}};rd.readAsText(f)});
clearBet();renderAll();renderGenerated();sync();
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{});
})();
