'use strict';
const C=window.EuroCore,$=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(Number(n)||0),datePT=s=>s?new Intl.DateTimeFormat('pt-PT',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(s+'T12:00:00')):'—';
const STORE='eurolab.v4';
const SEED_RESULTS=[{date:'2026-07-31',numbers:[10,24,25,31,45],stars:[4,5],m1:'NFN37781',source:'Jogos Santa Casa',official:true},{date:'2026-08-04',numbers:[25,30,34,46,50],stars:[1,12],m1:'',source:'Resultado oficial',official:true}];
const SEED_TICKETS=[{id:'20260731',drawDate:'2026-07-31',numbers:[18,20,23,44,47],stars:[1,2],mCode:'NDL16327',cost:2.5,prize:0}];
const PREVIOUS_SUGGESTIONS=[{date:'2026-08-04',numbers:[7,19,32,42,46],stars:[3,11]}];
function load(){try{return JSON.parse(localStorage.getItem(STORE))||null}catch{return null}}
const saved=load();const state=saved||{tickets:SEED_TICKETS,results:SEED_RESULTS,budget:10,suggestion:null,lastSync:null};
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function uuid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function balls(line){if(!line)return '<span class="mut">Sem dados</span>';return line.numbers.map(n=>`<span class="ball">${n}</span>`).join('')+'<span class="plus">+</span>'+line.stars.map(n=>`<span class="ball star">${n}</span>`).join('')}
function resultFor(date){return [...state.results].sort((a,b)=>b.date.localeCompare(a.date)).find(r=>r.date===date)||null}
function latestResult(){return [...state.results].sort((a,b)=>b.date.localeCompare(a.date))[0]||null}
function ticketStatus(t){const r=resultFor(t.drawDate),h=C.hits(t,r);return {h,cat:C.category(h)}}
function upsertResult(r){if(!r||!C.validLine(r.numbers,r.stars))return false;const clean={date:r.date,numbers:C.uniqSort(r.numbers),stars:C.uniqSort(r.stars),m1:(r.m1||'').toUpperCase(),source:r.source||'Atualização automática',official:r.official!==false};const i=state.results.findIndex(x=>x.date===clean.date);if(i>=0)state.results[i]=clean;else state.results.push(clean);return true}
function ensureSuggestion(force=false){const d=C.nextDrawISO(new Date());if(!force&&state.suggestion?.date===d)return;const lines=[...state.tickets,...PREVIOUS_SUGGESTIONS.map(x=>({numbers:x.numbers,stars:x.stars}))];state.suggestion={date:d,...C.generateBest({existing:lines,count:1,mode:'diversified'})[0]};save()}
function renderDashboard(){const lr=latestResult();$('latestDate').textContent=lr?datePT(lr.date):'Sem resultado';$('latestBalls').innerHTML=balls(lr);$('latestSource').textContent=lr?`${lr.source||'Resultado'}${lr.official?' · confirmado':''}`:'';ensureSuggestion();$('nextDrawLabel').textContent=datePT(state.suggestion.date);$('suggestionBalls').innerHTML=balls(state.suggestion);const spent=state.tickets.reduce((a,t)=>a+Number(t.cost||0),0),won=state.tickets.reduce((a,t)=>a+Number(t.prize||0),0);$('spent').textContent=money(spent);$('won').textContent=money(won);$('balance').textContent=money(won-spent);$('ticketCount').textContent=state.tickets.length;$('recentTickets').innerHTML=state.tickets.length?[...state.tickets].sort((a,b)=>b.drawDate.localeCompare(a.drawDate)).slice(0,4).map(ticketHTML).join(''):'<div class="empty">Ainda não há apostas.</div>'}
function ticketHTML(t){const st=ticketStatus(t),hit=st.h.n==null?'Por verificar':`${st.h.n} número(s) + ${st.h.s} estrela(s)`;return `<div class="ticket"><div class="row"><div><h4>${datePT(t.drawDate)}</h4><div class="meta">${money(t.cost)} · ${hit}</div></div><span class="pill ${st.cat==='Sem prémio'?'bad':st.cat==='Por verificar'?'info':'ok'}">${st.cat}</span></div><div class="balls">${balls(t)}</div><div class="actions"><button class="btn secondary" data-edit-ticket="${t.id}">Editar</button><button class="btn secondary" data-result-ticket="${t.id}">Resultado</button><button class="btn danger" data-delete-ticket="${t.id}">Eliminar</button></div></div>`}
function renderTickets(){$('ticketList').innerHTML=state.tickets.length?[...state.tickets].sort((a,b)=>b.drawDate.localeCompare(a.drawDate)).map(ticketHTML).join(''):'<div class="empty">Sem apostas.</div>'}
function resultHTML(r){return `<div class="ticket"><div class="row"><div><h4>${datePT(r.date)}</h4><div class="meta">${r.source||''}</div></div><span class="pill ${r.official?'ok':'info'}">${r.official?'Confirmado':'Manual'}</span></div><div class="balls">${balls(r)}</div></div>`}
function renderResults(){const lr=latestResult();$('resultOfficial').innerHTML=lr?resultHTML(lr):'<div class="empty">Sem resultado.</div>';$('resultList').innerHTML=[...state.results].sort((a,b)=>b.date.localeCompare(a.date)).map(resultHTML).join('')}
function renderBudget(){const now=new Date(),ym=now.toISOString().slice(0,7),spent=state.tickets.filter(t=>t.drawDate.startsWith(ym)).reduce((a,t)=>a+Number(t.cost||0),0);$('budget').value=state.budget;$('budgetStatus').textContent=`Este mês: ${money(spent)} de ${money(state.budget)} · ${spent<=state.budget?'dentro do limite':'limite ultrapassado'}`}
function renderAll(){renderDashboard();renderTickets();renderResults();renderBudget();$('syncText').textContent=state.lastSync?`Atualizado ${new Date(state.lastSync).toLocaleString('pt-PT')}`:'Pronto'}
function makeInputs(containerId,count,cls,max){$(containerId).innerHTML=Array.from({length:count},()=>`<input class="${cls}" type="number" min="1" max="${max}" required>`).join('')}
makeInputs('ticketNums',5,'ticket-num',50);makeInputs('ticketStars',2,'ticket-star',12);makeInputs('resultNums',5,'result-num',50);makeInputs('resultStars',2,'result-star',12);
function getValues(sel){return [...document.querySelectorAll(sel)].map(x=>Number(x.value))}
function fillValues(sel,values){[...document.querySelectorAll(sel)].forEach((x,i)=>x.value=values?.[i]??'')}
function clearTicket(){$('ticketId').value='';$('ticketTitle').textContent='Registar aposta';$('ticketForm').reset();$('ticketCost').value='2.50';$('ticketPrize').value='0';$('ticketDate').value=C.nextDrawISO(new Date());fillValues('.ticket-num',[]);fillValues('.ticket-star',[])}
function switchPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('on',x.id===id));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('on',x.dataset.page===id));window.scrollTo(0,0)}
$('nav').addEventListener('click',e=>{const b=e.target.closest('button[data-page]');if(b)switchPage(b.dataset.page)});
$('ticketForm').addEventListener('submit',e=>{e.preventDefault();const numbers=C.uniqSort(getValues('.ticket-num')),stars=C.uniqSort(getValues('.ticket-star'));if(!C.validLine(numbers,stars)){alert('Confirma 5 números diferentes (1–50) e 2 estrelas diferentes (1–12).');return}const id=$('ticketId').value||uuid(),t={id,drawDate:$('ticketDate').value,numbers,stars,cost:Number($('ticketCost').value||0),prize:Number($('ticketPrize').value||0),mCode:$('ticketM1').value.trim().toUpperCase()};const i=state.tickets.findIndex(x=>x.id===id);if(i>=0)state.tickets[i]=t;else state.tickets.push(t);save();clearTicket();renderAll();switchPage('tickets')});
$('cancelTicket').addEventListener('click',clearTicket);
document.body.addEventListener('click',e=>{const edit=e.target.closest('[data-edit-ticket]'),del=e.target.closest('[data-delete-ticket]'),res=e.target.closest('[data-result-ticket]');if(edit){const t=state.tickets.find(x=>x.id===edit.dataset.editTicket);if(!t)return;$('ticketId').value=t.id;$('ticketTitle').textContent='Editar aposta';$('ticketDate').value=t.drawDate;$('ticketCost').value=t.cost;$('ticketPrize').value=t.prize||0;$('ticketM1').value=t.mCode||'';fillValues('.ticket-num',t.numbers);fillValues('.ticket-star',t.stars);switchPage('tickets')}if(del){if(confirm('Eliminar esta aposta?')){state.tickets=state.tickets.filter(x=>x.id!==del.dataset.deleteTicket);save();renderAll()}}if(res){const t=state.tickets.find(x=>x.id===res.dataset.resultTicket);if(!t)return;const r=resultFor(t.drawDate);$('resultDate').value=t.drawDate;if(r){fillValues('.result-num',r.numbers);fillValues('.result-star',r.stars);$('resultM1').value=r.m1||''}else{fillValues('.result-num',[]);fillValues('.result-star',[]);$('resultM1').value=''}switchPage('results')}});
$('resultForm').addEventListener('submit',e=>{e.preventDefault();const r={date:$('resultDate').value,numbers:C.uniqSort(getValues('.result-num')),stars:C.uniqSort(getValues('.result-star')),m1:$('resultM1').value.trim().toUpperCase(),source:'Introdução manual',official:false};if(!upsertResult(r)){alert('Resultado inválido.');return}save();renderAll();alert('Resultado guardado e aplicado às apostas dessa data.')});
$('playSuggestion').addEventListener('click',()=>{ensureSuggestion();const key=C.lineKey(state.suggestion),exists=state.tickets.some(t=>t.drawDate===state.suggestion.date&&C.lineKey(t)===key);if(!exists)state.tickets.push({id:uuid(),drawDate:state.suggestion.date,numbers:[...state.suggestion.numbers],stars:[...state.suggestion.stars],cost:2.5,prize:0,mCode:''});save();renderAll();switchPage('tickets')});
$('newSuggestion').addEventListener('click',()=>{ensureSuggestion(true);renderAll()});
function explainMode(m){return {diversified:'Equilibra pares/ímpares, baixos/altos, dispersão e evita padrões óbvios.',pure:'Cada combinação é criada aleatoriamente, sem filtros.',share:'Favorece mais números acima de 31 para reduzir padrões de datas e potencial partilha.',history:'Usa frequências históricas apenas com peso leve; não prevê o próximo sorteio.'}[m]}
function generate(){const count=Math.max(1,Math.min(20,Number($('genCount').value)||1)),mode=$('genMode').value,lines=C.generateBest({existing:state.tickets,count,mode});$('generated').innerHTML=lines.map((l,i)=>`<div class="generated"><b>Linha ${i+1}</b><div class="balls">${balls(l)}</div></div>`).join('');$('genCost').value=money(count*2.5);$('genOdds').value='1 em '+Math.round(C.oddsForLines(count)).toLocaleString('pt-PT');$('genExplain').textContent=explainMode(mode)}
$('generate').addEventListener('click',generate);$('genCount').addEventListener('input',generate);$('genMode').addEventListener('change',generate);
$('budget').addEventListener('change',()=>{state.budget=Math.max(0,Number($('budget').value)||0);save();renderBudget()});
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('exportJson').addEventListener('click',()=>download('euromilhoes-lab-backup.json',JSON.stringify(state,null,2)));
$('importJson').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const d=JSON.parse(rd.result);if(!Array.isArray(d.tickets)||!Array.isArray(d.results))throw Error();Object.assign(state,d);save();renderAll();alert('Dados importados.')}catch{alert('Ficheiro inválido.')}};rd.readAsText(f)});
$('resetData').addEventListener('click',()=>{if(confirm('Apagar apostas e dados pessoais guardados neste dispositivo?')){localStorage.removeItem(STORE);location.reload()}});
async function syncOfficial(show=false){$('syncText').textContent='A procurar resultado…';try{const r=await fetch('latest-result.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();if(!upsertResult(data))throw Error('Dados inválidos');state.lastSync=new Date().toISOString();save();renderAll();if(show)alert('Resultado atualizado.')}catch(err){$('syncText').textContent='Sem atualização automática · modo manual disponível';if(show)alert('A fonte automática não respondeu. Podes inserir o resultado manualmente em Resultados.')}}
$('syncBtn').addEventListener('click',()=>syncOfficial(true));$('syncBtn2').addEventListener('click',()=>syncOfficial(true));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&(!state.lastSync||Date.now()-new Date(state.lastSync).getTime()>15*60*1000))syncOfficial(false)});
clearTicket();$('resultDate').value=latestResult()?.date||new Date().toISOString().slice(0,10);ensureSuggestion();renderAll();generate();syncOfficial(false);
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').then(r=>r.update()).catch(()=>{});
window.__EUROLAB_STATE__=state;
